//TYPES IS BASICALLY JUST A CONSTANT/FILE IS JUST A COLLECTON OF THESE
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const LOGOUT_CURRENT_ADMIN = 'LOGOUT_CURRENT_ADMIN'; // james
